$ANSIBLE_VAULT;1.1;AES256
64303232386365373734633638336635663966356562363361626362373966323166396364303533
3766363063633662616633363865396236363732366461650a366338373233633862316338303733
66393639636234653934313432303238623862323232613964326436663331353066343662366431
6430353937303362380a336437666463313863633437613539373736636338663135323538343763
31353563343764366465376236666637643934666335663166656264363665306434616537386530
37373966663236356439326461323235373131383931323831313663393863323032376136383732
34326436626332623863336234373361336166643366373864636332643361303166303064366637
63363536616432303938616665336366623035336331326536303065386338363634343665396439
36353538333839613738363235323333343736363965636661303662313565343963383032393037
37393734326666333938326264626361303330323632326236396539336138636430333334333265
34366363633830333832646437366163373333323966353234343166663263646239326437303065
63623439356434656264386461396139346164653031643530663331326464396238343333336461
66396532616462666137336663616133306566383635623737383866626664303462666134653232
33343535373337393232613530313135326339356336613539383762356566353530336361323163
30323231393438333366356663616530626135643731363434316163336331353366373161653939
61313032663166373231303261383939353830626661616232386365303834633837663133373430
63333639343036333433393066386665663535663264643364373232396336636665356238373437
3932646336316466313738386364336661306662386563636163
