$ANSIBLE_VAULT;1.1;AES256
66626331383265376462393762376662376331333565633138303666623863613935336661643930
3230393136653332613763623061346462376465346565320a316266326434326332393264363665
36383161363465343431663732313436306137376233383331356431623331303435643436366561
3637343238613264640a396661663030616261616638663065646163613164663334343735653034
39366431643335646332373065373634326638663330303135396437336665393133333230316261
39353666663137626439396264333462366265396366376432613732666235663965303864326662
61623165386261303039626464323464326236313534653166653563633764373034376336373936
64636436366533316132303666376237343734306137316235326466656138313330633664636136
62343166346262663761633030656236393330363165383666333236626437346634623434636239
65336637303836323239663639643063363236353265313038656164326138396239316462646566
39666266313337623361336237636163326434653235623562363939393436396231616461663935
32306263646236666234653164636337313533303762336432336239643033636431363135663761
65303535333937356664343739303566626433363963353837323736343763663238346238346363
63656239653630353433383065356631383264633961656665353136353138336630343764613535
36623034353635343861633835656164626264393439666435393439383464656534383666666464
65653330653463643433
